### ISSUE TITLE
Have to uninistall to log out when the server is inaccessible

### ISSUE THREAD

**Issue by ieure** [UnicornsOnLSD/finamp#169]
I recently moved my Jellyfin instance from HTTP to HTTPS.  The hostname is the same, and it *should* be transparently redirecting any insecure request to the new location, but, Finamp really dislikes this change.  It refuses to operate, which I can understand, but it also won't let me log out / back in to correct it.  Instead, I have to completely uninstall the app, reinstall it, and re-log-in.

The Android Jellyfin app noticed that the server it was configured with wasn't working, and kicked me back to the login screen.  It'd be great if Finamp could do the same.

**Comment by UnicornsOnLSD** [comment]
The issue of logging out not working was fixed quite early on in 0.6's development (commit c221ba8261b5c9b88f1d1b87ca6425a47e0d19fa specifically, all the way back in September). I've had a few people complain about it being broken and I should have probably released a hotfix when I made the fix. Bringing the user to login may be a better idea, but it'd probably be a pain to implement. I'll keep this issue open with a new title though.

**Comment by UnicornsOnLSD** [comment]
Actually, it would be very rare for a connection to not be made and the user wanting to log out. For example, if you're offline, you don't want to be thrown to the login screen since offline mode will still work. HTTP 401 (unauthorised) has an explanation when you click on "More" on the error snackbar saying to logout and login. It's probably not as nice as automatically being taken to login but that would be a lot of work for not a lot of benefit.
