### ISSUE TITLE
Publish .ipa from CI

### ISSUE THREAD

**Issue by crobibero** [UnicornsOnLSD/finamp#18]
Hi,

Can you please publish the ipa for iOS that's generated via CI? I would like to try to install it on my phone using [altserver](https://altstore.io)

**Comment by UnicornsOnLSD** [comment]
Just tried to generate an IPA and I can't because I'm not enrolled in the Apple Developer Program. Unless somebody else decides to start building IPAs, there is currently no way to use Finamp on iOS without being a verified developer :(

As I said in the readme, I'll be able to enroll in a few months.
