### ISSUE TITLE
latest version can not login

### ISSUE THREAD

**Issue by charleypeng** [UnicornsOnLSD/finamp#216]
i have downloaded the latest version and when click login the error shows below
![image](https://user-images.githubusercontent.com/2144710/163303218-fbe78274-c14d-4b6b-bb92-d5e9e2ff579e.png) 

iOS version 15.4
jellyfin version 10.7.7
server address is confirmed in right format.

**Comment by UnicornsOnLSD** [comment]
This is due to the kanji in your device name - the name is sent as a HTTP header, which only allows ASCII text. Currently, I only filter out apostrophes as iOS uses a non-ASCII apostrophe in the device name by default, at least when the language is set to English.

For 0.6.1, I will properly filter out any non-ASCII characters. For now, removing the kanji in your device name should fix the issue.

**Comment by UnicornsOnLSD** [comment]
Fixed in 0013c92

**Comment by UnicornsOnLSD** [comment]
Just pushed this change as a release, should be out on iOS in the next few days

**Comment by charleypeng** [comment]
> Just pushed this change as a release, should be out on iOS in the next few days

cool
