### ISSUE TITLE
Permission denied when creating directory

### ISSUE THREAD

**Issue by ThibaultNocchi** [UnicornsOnLSD/finamp#31]
Hello,

When trying to download on my SD card on Android, I get a permission denied error in the logs and nothing gets downloaded.

![Screenshot_20210501-102419.jpg](https://user-images.githubusercontent.com/1619359/116776198-6fdc6400-aa67-11eb-9934-a40ec247d54b.jpg)

(I've screenshotted the error cause copying the logs copies all of it and it's hard to remove the useless stuff, maybe we could long press on a log item to copy it? :))

**Comment by UnicornsOnLSD** [comment]
Did you deny the permission? I can't reproduce this. Even if I remove the permissions from settings, it still requests permission. What Android version are you running?

**Comment by ThibaultNocchi** [comment]
Nope I allowed and tried, uninstalled, allowed and tried again and got the same problem. I'm on Android 8, I'm open to any testing ^^

**Comment by Kiniou-Bouzou** [comment]
I have the same issue.
Android 10 on Huawei Mate 20 Pro
Open for testing too if I can help.

Great application by the way!

**Comment by UnicornsOnLSD** [comment]
@ThibaultNocchi @Kiniou-Bouzou Can you try downloading something to your internal storage? Just want to make sure that this is an issue with SD cards specifically.

**Comment by ThibaultNocchi** [comment]
I can confirm I can download and play songs with the internal storage

**Comment by UnicornsOnLSD** [comment]
@ThibaultNocchi Should have clarified, make a custom storage location on your phone's local storage (like in the music directory) instead of the SD card

**Comment by ThibaultNocchi** [comment]
I also confirm that it works with a custom internal storage path :)

**Comment by UnicornsOnLSD** [comment]
That's weird. Do other apps have issues writing to the SD card?

If possible, could you run "ls -l /storage/ACBD-E0C8/" on something like Termux and send the result? I've seen some people talking about read-only SD card stuff. As I said, I can't replicate this on an emulator. It seems that Android has started to really lock down on external access with stuff like scoped storage, and Flutter's external storage support isn't formally documented (https://github.com/flutter/flutter/issues/40504).

I think it is possible, since it worked on the emulator. It's probably just Android being Android.

**Comment by ThibaultNocchi** [comment]
When mounting my phone via USB on Linux, everything is 700 with my user as owner and group on my SD.

**Comment by UnicornsOnLSD** [comment]
@ThibaultNocchi @Kiniou-Bouzou I've just made a new dialog in the new-storage-selector branch that shows the app's "internal" storage locations. This should also include a directory on your SD card. Could you try this? You can access this menu by pressing the SD card icon button on the download locations screen (top right). It's not a perfect solution since this directory is still hidden from the user, but I might add it as an option if it increases compatibility.

Also, this includes the ability to long press on logs to copy them.

[app-arm64-v8a-release.zip](https://github.com/UnicornsOnLSD/finamp/files/6428471/app-arm64-v8a-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/UnicornsOnLSD/finamp/files/6428473/app-armeabi-v7a-release.zip)
[app-x86_64-release.zip](https://github.com/UnicornsOnLSD/finamp/files/6428475/app-x86_64-release.zip)

**Comment by ThibaultNocchi** [comment]
It worked for me! Thanks! :)

**Comment by Kiniou-Bouzou** [comment]
It works as well for me.
Thank you

**Comment by Kiniou-Bouzou** [comment]
It works!
Thank you #

**Comment by ThibaultNocchi** [comment]
Thanks a lot!
