### ISSUE TITLE
[Feature Request] Sign out button

### ISSUE THREAD

**Issue by WorkingSea** [UnicornsOnLSD/finamp#47]
I believe a button to easily log out would be appreciated so one doesn't have to clear the app data manually to insert a new address or log in a different account.

**Comment by UnicornsOnLSD** [comment]
That should be easy to do. Only issue would be how to handle currently downloaded songs, but I should be able to figure that out.

**Comment by Bitwolfies** [comment]
> That should be easy to do. Only issue would be how to handle currently downloaded songs, but I should be able to figure that out.

Personally I’d leave the songs until a user signs in with another account, in which you can prompt them to delete the old songs if they don’t plan to use the old account again.

**Comment by UnicornsOnLSD** [comment]
I might get add multi-user support along with this. The new update already has breaking changes that will require everyone to wipe their data, so I may as well clean up how I'm storing user-specific stuff.

I'll probably just allow downloads to be seen by all users of the same server. There isn't an easy way to completely separate downloads (the download manager will show downloads for all servers), but I should be able to separate downloads in the offline mode view. I won't separate them by ID since an item with the same path would presumably have the same contents. Pressing download would just "link" the downloaded items to that server, so offline mode can point to the already downloaded item. Either way, someone having the same content across two different servers will be rare, so I probably shouldn't spend too much time worrying about it. Also, it probably won't be important to separate downloads by user as I doubt many people are actually sharing one instance of Finamp across multiple people.

**Comment by UnicornsOnLSD** [comment]
Added in a878aa0ad4f1e88db968f5e21d2683656af35f34
