### ISSUE TITLE
Support TLS 1.3

### ISSUE THREAD

**Issue by kevincox** [UnicornsOnLSD/finamp#57]
After entering server information and logging in I get an error. 

> Error
>
> HandshakeException: Handshake error in client (0S Error:
TLSV1_ALERT_PROTOCOL_VERSION(tls_recor d.cc:587)

Version 0.4.3 from f-droid. 

Some logs after authentication. 

```
[Chopper/INFO] 2021-06-26 10:41:08.782328: --> POST https://jellyfin.example/Users/AuthenticateByName

null
[Chopper/INFO] 2021-06-26 10:41:08.782347: Content-Type: application/json; charset=utf-8

null
[Chopper/INFO] 2021-06-26 10:41:08.782353: X-Emby-Authorization: MediaBrowser Client="Finamp", Device="Redacted", DeviceId="redacted", Version="0.4.3"

null
```

**Comment by UnicornsOnLSD** [comment]
This may be an issue with how you have HTTPS set up with your server. How do you have your server setup with HTTPS (reverse proxy, cert provider etc)? Here's a StackOverflow issue where the answer is to explicitly add support for other versions of TLS: https://stackoverflow.com/questions/57321865/handshake-error-in-client-os-error-tlsv1-alert-protocol-versiontls-record-cc. I'd recommend you don't add TLS 1.1 though, since it's been deprecated.

**Comment by kevincox** [comment]
My server intentionally only supports TLS 1.3. Are you saying that finamp
only supports TLS 1.2?

In that case can we make this a feature request for TLS 1.3 support?

**Comment by UnicornsOnLSD** [comment]
Finamp just uses Dart/Flutter's standard HTTP stuff, so it's an issue there. It looks like this is being worked on/has been fixed in new Dart/Flutter versions (https://github.com/dart-lang/sdk/issues/41061). For now, I'd say you should wait for the new release, since Finamp's master branch currently has some unstable stuff and I'm planning on doing more breaking changes before the new release. You could also temporarily allow your server to accept TLS 1.2 if you don't want to wait.

**Comment by kevincox** [comment]
Ok. I'll wait for the next build. Thanks!

**Comment by UnicornsOnLSD** [comment]
Now that 0.5.0 is out, can you test this?

**Comment by kevincox** [comment]
I will as soon as the f-droid repo updates. It seems to be slightly stalled.

**Comment by kevincox** [comment]
Works perfectly, thanks!
