### ISSUE TITLE
Using album artist field instead of artist field

### ISSUE THREAD

**Issue by the-r0cket06** [UnicornsOnLSD/finamp#71]
I have a number of compilation albums, and all have Various Artist as the album artist field. When playing these, instead of showing the actual artist it simply shows various artist. This occurs on any screen that shows the artist and song title.

Can provide additional information if required.

**Comment by UnicornsOnLSD** [comment]
Album artist seems more concise to me, but I can make an option to show the artist instead of the album artist.

**Comment by XiaoKe89** [comment]
Album artist only works for albums that have a single artist. Any songs from compilation albums such as Soundtracks won't show under the artist of the song and will instead show as "Various Artists" as op started. This also is a little bothersome for tracks that have more that one artist as you can only find the song under whoever is listed as the album artist instead of either artist on the track. Gelli uses the Artist field instead of Album Artist so in the library you can find all songs by an artist regardless of whether or not they are the album artist. The display in now playing is annoying but it's more frustrating on the library section when it's hard to find a song by an artist because it's only listed under the album artist and the artist of the song isn't the album artist. So I will agree with OP that we either need an option or change the default entirely to use the song artist as opposed to the album artist

**Comment by UnicornsOnLSD** [comment]
Closing as I'm pretty sure I made this change a while ago
