### ISSUE TITLE
[Feature Request] Add option to hide song title & album cover in Android media player

### ISSUE THREAD

**Issue by enduring78** [UnicornsOnLSD/finamp#726]
I know this might be a niche feature request, but it would be really great to be able to hide the current song title and media art, and only show the playback position and media controls in the native Android media player. 

One reason someone might want this is if the currently playing media art does not fit in the lockscreen. Android used to offer a option to not show media art a few years back, but it was eventually removed. 

Another reason is when someone does not want others to see the currently playing song, perhaps in a professional setting.

**Comment by Chaphasilor** [comment]
Hmm, I think that's too niche of a feature to be honest. It's probably possible to do, but I doubt anyone but you would actually use that.  
What's *your* specific reason for requesting the feature? 🤔

**Comment by Chaphasilor** [comment]
How technically versed are you? The change is simple, but as I said, it doesn't qualify as a feature for the app imo.

But what you could do instead is fork the app, create a new branch, and there apply your change. Then you can build your own custom version, and would be able to "easily" get the latest updates of the regular version too.

**Comment by Chaphasilor** [comment]
Sure! Here in the repo, there's a file called "CONTRIBUTING.md", which should have most of the info to get you started. It's also linked in the readme.

Once you have the regular app working, I can point you to the needed changes, or even make the changes for you.

Let me know if you need any help with the setup!

**Comment by Chaphasilor** [comment]
Well if you read the error message, it says "not enough disk space". I know that problem very well ^^  
That means Flutter + Finamp aren't even trying to start yet.

At this point, instead of using an emulator, I'd suggest simply connecting your phone via USB, enabling USB debugging on it (in the developer settings), and then using your phone to debug the app!  
You should find detailed instructions for that online.

To test out if Flutter is working correctly, you can run the command `flutter build apk --debug` from a terminal within the base/root of the project. That should build the debug APK, without installing/launching it yet.

**Comment by Chaphasilor** [comment]
Any progress? :)

**Comment by Chaphasilor** [comment]
Hey, sorry about not replying earlier!

The needed change is here:
https://github.com/jmshrv/finamp/blob/redesign/lib/services/queue_service.dart#L1056-L1059

You'd simply need to comment these out, or replace them with generic strings.

**Comment by Chaphasilor** [comment]
Hey, that's great to hear! Did you also manage to merge in the changes of the 0.9.10 and 0.9.11 updates? If you're struggling with it, I could help you out ^^
