### ISSUE TITLE
Exclude local downloads from device backups (iOS backup to macOS via Finder)

### ISSUE THREAD

**Issue by notDavid** [UnicornsOnLSD/finamp#849]
Hi there,

i'm trying to figure out where the Downloads folder is, but can't seem to locate it (i did not change the default.) I assume it's in a container not visible to the user;

- Could you please clarify whether the downloads folder is excluded from local device backups? (backups of an iOS device on macOS, via Finder.)

Finamp 0.9.9 (TestFlight)

Thank you!

**Comment by jmshrv** [comment]
I mark the downloads folder (inside the app directory, it isn't user-visible) as excluded from backups, so I'd assume that extends to local backups :)

https://github.com/jmshrv/finamp/blob/2b086439e585efc2dc7511698124474d054da2f3/ios/Runner/AppDelegate.swift#L21-L26

(the function references iCloud since that was why I initially did it, but `isExcludedFromBackup` should handle local backups too)
