### ISSUE TITLE
Played songs are not visible on the server

### ISSUE THREAD

**Issue by enduring78** [UnicornsOnLSD/finamp#895]
When playing music with FInamp, it (I think locally) shows how many times I have played that song.

This is great, but seems to not be reported to the server, kinda 'breaking'  the playback reports. 

This seems to be affecting mainly songs played in offline mode, but not all songs played in online mode are listed as well.

**Comment by Chaphasilor** [comment]
Well, anything played in offline mode is not reported at all, since Jellyfin doesn't allow us to retro-actively report playback. But Finamp has been keeping track of offline playback since a few months at this point, and you can access that data by going to the "Playback History" screen and clicking the share button at the top right. It will give you a file that lists playback events for your tracks.

I'm not sure why tracks wouldn't be reported when offline. Finamp reports playback to the server at all times, and you can see that on your server's admin dashboard, and in the activity log. It will even keep a paused the session active in the background (if the app isn't killed by the system), so that if you resume playback later on it's still counted as a single play.  
If you could pinpoint the issue or figure out which tracks in particular are affected, that would help a lot!

**Comment by Chaphasilor** [comment]
I see, that is very helpful! I'll try to figure out why it's not reporting correctly after disabling offline mode!  

Jellyfin Rewind? Never heard of it... :P  
I can try to create a script that uploads the offline playback data from Finamp into the Playback Reporting plugin. Those plays won't be show in Jellyfin, since they'd only be added to the plugin's database, and not the main Jellyfin database, but they would be used in Jellyfin Rewind. It all depends on if I can actually modify the Playback Reporting database. Might only be possible with an admin account, or not at all...

**Comment by Chaphasilor** [comment]
Just gave it a try, importing the offline playback data into the plugin database is possible, even for non-admin users (which means non-admin users are probably also able to delete the entire playback reporting database, yay...).  
So you can expect some kind of import tool in this year's Jellyfin Rewind (for Finamp users at least).

**Comment by Chaphasilor** [comment]
It would be a section or page in Jellyfin Rewind where you can upload the offline log file from Finamp, along with some instructions on how to get that :)

But, regarding your playback count issue: I tried to replicate the issue, but for me everything seems to work just fine. Enabling offline mode and then selecting something to play results in the track not being reported at first (since Finamp is offline), and then as soon as I disable offline mode, the dashboard shows the currently playing track and the play count is incremented. Any following tracks in the queue also have their play count incremented once played.

I assume you're still using your custom Finamp build, based on a recent beta? If so, which version are you based on? And would you mind sending both Finamp logs and a screenshot of the "Activity" page in Jellyfin after the tracks are not properly reported?

**Comment by Chaphasilor** [comment]
@enduring78 any updates? :)
