### ISSUE TITLE
Play in the background 

### ISSUE THREAD

**Issue by screwfaze** [UnicornsOnLSD/finamp#99]
When you close all open apps finamp does not continue in the background but closes down.
Also when you start it back up the queue is not remembered which would be a good feature.

Thanks

**Comment by UnicornsOnLSD** [comment]
Fixed audio stopping in 90e37e6, the queue should also stay now in the next release

**Comment by screwfaze** [comment]
When next release?

**Comment by UnicornsOnLSD** [comment]
When it's ready ™, if you're on Android I can make an APK for now

**Comment by screwfaze** [comment]
> When it's ready ™, if you're on Android I can make an APK for now

If you can release apk that would be awesome, happy to test and report back any issues.

**Comment by UnicornsOnLSD** [comment]
Here's an APK that includes this change. There may be some bugs since this also includes a big overhaul to the way that the app plays audio, but it should be fine. As I said, this is still a work-in-progress :)

[app-release.zip](https://github.com/UnicornsOnLSD/finamp/files/7073444/app-release.zip)
